# shellcheck shell=bash
source /etc/makepkg.conf

# Local archival builds favor size over compressor wall time.
COMPRESSGZ=(gzip -c -f -n -9)
COMPRESSXZ=(xz -c -z -T0 -9e -)
COMPRESSZST=(zstd -c -z -T0 -q --ultra -22 -)
PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.xz'
